server:
  port: 8085
spring:
  application:
    name: product-delivery-admin-server
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: http://config:config-password@192.168.56.1:8888
