name: productdelivery
services:
  # Infrastructure
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.7
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - './config/keycloak/import:/opt/keycloak/data/import'
    ports:
      - '8082:8080'
    command: start-dev --import-realm
  tempo:
    image: grafana/tempo:2.3.1
    command: -config.file=/etc/tempo.yaml
    volumes:
      - './config/tempo/tempo.yaml:/etc/tempo.yaml'
    ports:
      - '3200:3200'
      - '9095:9095'
      - '4317:4317'
      - '4318:4318'
      - '9411:9411'
      - '14268:14268'
  loki:
    image: grafana/loki:2.9.4
    ports:
      - '3100:3100'
  grafana:
    image: grafana/grafana:10.2.4
    ports:
      - '3000:3000'
    volumes:
      - './data/grafana:/var/lib/grafana'
    user: '1000'
  victoria-metrics:
    image: victoriametrics/victoria-metrics:v1.93.12
    command: -promscrape.config=/promscrape.yaml
    volumes:
      - './config/victoria-metrics/promscrape_docker_compose.yaml:/promscrape.yaml'
    ports:
      - '8428:8428'
  catalog-db:
    image: postgres:16
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: catalog
      POSTGRES_PASSWORD: catalog
      POSTGRES_DB: catalog
  feedback-db:
    image: mongo:7
    ports:
      - '27018:27017'
  #Services
  config-server:
    restart: always
    build:
      dockerfile: Dockerfile
      args:
        JAR_FILE: config-server/target/config-server-0.0.1-SNAPSHOT-exec.jar
      tags:
        - localhost:5000/productdelivery/config-server:0.0.1
    environment:
      SPRING_PROFILES_ACTIVE: native
      SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS: file:///config/{application}/{profile}
      LOKI: http://loki:3100
    volumes:
      - './config/cloud:/config'
    ports:
      - '8888:8888'
  eureka-server:
    restart: always
    build:
      dockerfile: Dockerfile
      args:
        JAR_FILE: eureka-server/target/eureka-server-0.0.1-SNAPSHOT-exec.jar
      tags:
        - localhost:5000/productdelivery/eureka-server:24.1.1
    environment:
      SPRING_PROFILES_ACTIVE: cloudconfig
      LOKI: http://loki:3100
    ports:
      - '8761:8761'
  admin-server:
    restart: always
    build:
      dockerfile: Dockerfile
      args:
        JAR_FILE: admin-server/target/admin-server-0.0.1-SNAPSHOT-exec.jar
      tags:
        - localhost:5000/productdelivery/admin-server:24.1.1
    environment:
      SPRING_PROFILES_ACTIVE: cloudconfig
      LOKI: http://loki:3100
    ports:
      - '8085:8085'
  product-service:
    restart: always
    build:
      dockerfile: Dockerfile
      args:
        JAR_FILE: product-service/target/product-service-0.0.1-SNAPSHOT-exec.jar
      tags:
        - localhost:5000/productdelivery/product-service:24.1.1
    environment:
      SPRING_PROFILES_ACTIVE: cloudconfig
      LOKI: http://loki:3100
    ports:
      - '8081:8081'
  feedback-service:
    restart: always
    build:
      dockerfile: Dockerfile
      args:
        JAR_FILE: feedback-service/target/feedback-service-0.0.1-SNAPSHOT-exec.jar
      tags:
        - localhost:5000/productdelivery/feedback-service:24.1.1
    environment:
      SPRING_PROFILES_ACTIVE: cloudconfig, gateway
      LOKI: http://loki:3100
    ports:
      - '8084:8084'
  customer-service:
    restart: always
    build:
      dockerfile: Dockerfile
      args:
        JAR_FILE: customer-service/target/customer-service-0.0.1-SNAPSHOT-exec.jar
      tags:
        - localhost:5000/productdelivery/customer-service:24.1.1
    environment:
      SPRING_PROFILES_ACTIVE: cloudconfig, gateway
      LOKI: http://loki:3100
    ports:
      - '8083:8083'
  manager-service:
    restart: always
    build:
      dockerfile: Dockerfile
      args:
        JAR_FILE: manager-service/target/manager-service-0.0.1-SNAPSHOT-exec.jar
      tags:
        - localhost:5000/productdelivery/manager-service:24.1.1
    environment:
      SPRING_PROFILES_ACTIVE: cloudconfig
      LOKI: http://loki:3100
    ports:
      - '8080:8080'
  api-gateway:
    restart: always
    build:
      dockerfile: Dockerfile
      args:
        JAR_FILE: api-gateway/target/api-gateway-0.0.1-SNAPSHOT-exec.jar
      tags:
        - localhost:5000/productdelivery/api-gateway:24.1.1
    environment:
      SPRING_PROFILES_ACTIVE: cloudconfig
      LOKI: http://loki:3100
    ports:
      - '8086:8086'