productdelivery:
  services:
    catalog:
      uri: lb://product-delivery-product-service
      registration-id: keycloak
spring:
  boot:
    admin:
      client:
        enabled: false
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://192.168.56.1:8082/realms/product-delivery
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: manager-service
            client-secret: 2OIPIWwv67AMc5o2MPf54a4uuGwBGqmZ
            scope:
              - openid
              - view_catalog
              - edit_catalog
              - microprofile-jwt
          metrics:
            provider: keycloak
            client-id: manager-service
            client-secret: 2OIPIWwv67AMc5o2MPf54a4uuGwBGqmZ
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
          discovery:
            provider: keycloak
            client-id: manager-service
            client-secret: 2OIPIWwv67AMc5o2MPf54a4uuGwBGqmZ
            authorization-grant-type: client_credentials
            scope:
              - discovery
      resourceserver:
        jwt:
          issuer-uri: http://192.168.56.1:8082/realms/product-delivery
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  zipkin:
    tracing:
      endpoint: http://192.168.56.1:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
eureka:
  instance:
    hostname: 192.168.56.1
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 1
  client:
    registryFetchIntervalSeconds: 1
    service-url:
      defaultZone: http://192.168.56.1:8761/eureka/
