server:
  port: 8086
  forward-headers-strategy: framework
spring:
  application:
    name: product-delivery-api-gateway
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: http://config:config-password@192.168.56.1:8888
