spring:
  boot:
    admin:
      client:
        enabled: false
  data:
    mongodb:
      uri: mongodb://192.168.56.1:27018/feedback
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: feedback-service
            client-secret: BWYUHoRNRdyGyU6nMAkX4Neax0x74Jj8
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
          discovery:
            provider: keycloak
            client-id: feedback-service
            client-secret: BWYUHoRNRdyGyU6nMAkX4Neax0x74Jj8
            authorization-grant-type: client_credentials
            scope:
              - discovery
        provider:
          keycloak:
            issuer-uri: http://192.168.56.1:8082/realms/product-delivery
      resourceserver:
        jwt:
          issuer-uri: http://192.168.56.1:8082/realms/product-delivery
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  zipkin:
    tracing:
      endpoint: http://192.168.56.1:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 1
    hostname: 192.168.56.1
  client:
    registryFetchIntervalSeconds: 1
    service-url:
      defaultZone: http://192.168.56.1:8761/eureka/