productdelivery:
  services:
    catalog:
      uri: http://localhost:8081
      registration-id: keycloak
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/manager
    username: manager
    password: manager
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/product-delivery
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: manager-app
            client-secret: 2OIPIWwv67AMc5o2MPf54a4uuGwBGqmZ
            scope:
              - openid
              - view_catalog
              - edit_catalog
              - microprofile-jwt