server:
  port: 8080
productdelivery:
  services:
    catalog:
      uri: http://localhost:8081
      registration-id: keycloak
spring:
  application:
    name: product-delivery-manager-service
  boot:
    admin:
      client:
        url: http://localhost:8085
        instance:
          name: manager-service
          service-host-type: ip
        enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5433/manager
    username: manager
    password: manager
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://192.168.56.1:8082/realms/product-delivery
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: manager-app
            client-secret: 2OIPIWwv67AMc5o2MPf54a4uuGwBGqmZ
            scope:
              - openid
              - view_catalog
              - edit_catalog
              - microprofile-jwt
          metrics:
            provider: keycloak
            client-id: manager-app-metrics-client
            client-secret: sebNErjZ9jbihzuWxFMk6SOEURiEVO6I
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
      resourceserver:
        jwt:
          issuer-uri: http://192.168.56.1:8082/realms/product-delivery
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  zipkin:
    tracing:
      endpoint: http://192.168.56.1:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
