server:
  port: 8080
spring:
  application:
    name: product-delivery-manager-service
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: http://config:config-password@192.168.56.1:8888