server:
  port: 8083
productdelivery:
  services:
    catalog:
      uri: http://localhost:8081
    feedback:
      uri: http://localhost:8084
spring:
  application:
    name: customer-service
  boot:
    admin:
      client:
        url: http://localhost:8085
        instance:
          name: customer-service
          service-host-type: ip
        enabled: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://192.168.56.1:8082/realms/product-delivery
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: customer-app
            client-secret: S9dz26MPiCPlVNYDxobBun7gqBcYaFtq
            authorization-grant-type: authorization_code
            scope:
              - openid
              - view_catalog
          metrics:
            provider: keycloak
            client-id: customer-app-metrics-client
            client-secret: bOyLx1Dc18zfM75HuWoynBcd0CWbrt81
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
      resourceserver:
        jwt:
          issuer-uri: http://192.168.56.1:8082/realms/product-delivery
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'