server:
  port: 8081
spring:
  application:
    name: product-delivery-product-service
  boot:
    admin:
      client:
        url: http://localhost:8085
        instance:
          name: product-service
          service-host-type: ip
        enabled: true
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5434/catalog
    username: catalog
    password: catalog
  flyway:
    schemas:
      - public
      - catalog
  jpa:
    show-sql: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://192.168.56.1:8082/realms/product-delivery
        registration:
          keycloak:
            client-id: product-service-metrics-client
            client-secret: kJAnOCAFxLu6zoScDgReZEYj5wTok1WN
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
      resourceserver:
        jwt:
          issuer-uri: http://192.168.56.1:8082/realms/product-delivery
logging:
  level:
    sql: info
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  zipkin:
    tracing:
      endpoint: http://192.168.56.1:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
eureka:
  client:
    enabled: false