server:
  port: 8081
spring:
  application:
    name: product-delivery-product-service
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: http://config:config-password@localhost:8888
