spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/catalog
    username: catalog
    password: catalog
  flyway:
    schemas:
      - public
      - catalog
  jpa:
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/product-delivery
server:
  port: 8081
logging:
  level:
    sql: info
springdoc:
  swagger-ui:
    oauth:
      client-id: catalog-service-swagger-ui
      use-pkce-with-authorization-code-grant: true
keycloak:
  uri: http://localhost:8082