spring:
  security:
    user:
      name: catalog_service_user
      password: '{noop}password'
      roles:
        - SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5434/catalog
    username: catalog
    password: catalog
  flyway:
    schemas:
      - public
      - catalog
  jpa:
    show-sql: true

server:
  port: 8081

logging:
  level:
    sql: info