spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/catalog
    username: catalog
    password: catalog
  flyway:
    schemas:
      - public
      - catalog
  jpa:
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/product-delivery
server:
  port: 8081
logging:
  level:
    sql: info