server:
  port: 8761
spring:
  application:
    name: product-delivery-eureka-server
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: http://config:config-password@localhost:8888
