spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.56.1:8082/realms/product-delivery
      client:
        provider:
          keycloak:
            issuer-uri: http://192.168.56.1:8082/realms/product-delivery
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            client-id: admin-service
            client-secret: MMoPK3VxGWvYgTNGQrBcnpSkHfPSmUS1
            scope:
              - metrics
          login:
            provider: keycloak
            client-id: admin-service
            client-secret: MMoPK3VxGWvYgTNGQrBcnpSkHfPSmUS1
            scope:
              - metrics
              - openid
          discovery:
            provider: keycloak
            client-id: admin-service
            client-secret: MMoPK3VxGWvYgTNGQrBcnpSkHfPSmUS1
            authorization-grant-type: client_credentials
            scope:
              - discovery
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
eureka:
  instance:
    hostname: 192.168.56.1
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 1
  client:
    service-url:
      defaultZone: http://192.168.56.1:8761/eureka/
    registryFetchIntervalSeconds: 1
    register-with-eureka: false