server:
  port: 8084
spring:
  application:
    name: product-delivery-feedback-service
  boot:
    admin:
      client:
        url: http://localhost:8085
        instance:
          name: feedback-service
          service-host-type: ip
        enabled: true
  cloud:
    config:
      enabled: false
  data:
    mongodb:
      uri: mongodb://localhost:27018/feedback
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: feedback-service
            client-secret: BWYUHoRNRdyGyU6nMAkX4Neax0x74Jj8
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
        provider:
          keycloak:
            issuer-uri: http://192.168.56.1:8082/realms/product-delivery
      resourceserver:
        jwt:
          issuer-uri: http://192.168.56.1:8082/realms/product-delivery
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  zipkin:
    tracing:
      endpoint: http://192.168.56.1:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
eureka:
  client:
    enabled: false